### ISSUE TITLE
Adicionar dijkstra, para calculo do melhor caminho

### ISSUE THREAD

**Issue by Leacina** [AlissonSchmitz2/Projeto-PICII#7]

**Comment by wilianx7** [comment]
A princípio, o dijkstra deverá retornar os Ids das estantes que deverão ser pintadas.

A tela ResultadoCaminhoWindow usará esses Ids para pintar as estantes.

A lista completa com todas as estantes já está implementada na tela ResultadoCaminhoWindow.
